version: '3.8'

services:
  uploadit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Frontend
      - "3000:3000"  # Backend
    environment:
      - PORT=3000
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./src:/app/src
      - ./server:/app/server
      - ./node_modules:/app/node_modules
    networks:
      - uploadit-network

networks:
  uploadit-network:
    driver: bridge